### ISSUE TITLE
Browser- und Dokumententitel

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#10]
**BITV/WCAG-Prüfschritt: „Dokumenttitel sind eindeutig, sie bezeichnen Site und Seiteninhalt.“**

**Problem:** Als Dokumententitel wird „Geoportal Hessen“ angegeben. Dieser Titel ist nicht ausreichend

![dokumenten_title](https://user-images.githubusercontent.com/74015261/144473611-5a28fd49-0db7-49be-870a-88fad6c7a54d.png)

**Lösungsvorschlag:** Einen Dokumententitel entsprechend des Inhalts angeben, wie zum Beispiel: “Startseite – Geoportal Hessen“.

**Comment by Don-King-Kong** [comment]
Lösung:
Es muss das Dokument "/data/GeoPortal.rlp/templates/base.html" in Zeile 10 Angepasst werden.

- <title>Startseite: Geoportal {{ GEOPORTAL_IDENTIFIER }} {% block title %} {% endblock %}</title>
- [ ] Es muss geprüft werden, ob es Abhänigkeiten bzgl. den Englisch-Deutschen-Übersetzungen gibt, ggf. müssen die "Translation-Files" angepasst werden.

**Comment by Don-King-Kong** [comment]
Wenn man es richtig machen will, gibt es Abhängikeiten!

ich habe in `/data/GeoPortal.rlp/locale/de/LC_MESSAGES/django.po` folgende zeilen hinzugefügt
```
1676 #: templates/base.html:10
1677 msgid "Homepage"
1678 msgstr "Startseite"
```
In `/data/GeoPortal.rlp/templates/base.htm` habe ich die Zeile 10 mit einem **trans** block ergänzt
 10     <title>{% trans 'Homepage' %} Geoportal {{ GEOPORTAL_IDENTIFIER }} {% block title %} {% endblock %}</title>

Hab den Apache neugestartet, allerdings bekomme ich nur Homepage ohne deutsche Übersetzung angezeigt.

**Comment by karlbrink** [comment]
hi,
bei Anpassung der django.po muss Kap 8.10 des Handbuches befolgt werden.

Die statische Anpassung im Template reicht nicht mit und ohne Übersetzung. Dann ist der Titel immer Homepage Geoportal Hessen - auch wenn ich im Kartenviewer bin oder in der Suche oder auf Meldungen oder Hilfe usw...

Der Titel sollte Geoportal Hessen bleiben, oder er muss dynamisch angepasst werden, je nachdem was der Nutzer zu sehen bekommt.

**Comment by Andreasr28** [comment]
This issue isn't in Progress anymore. What happended?

**Comment by muqit-zoarder** [comment]
I have noticed some translation problem in my version of frontpage.js , please see in the push branch. I copied again frontpage.js file from git repo and saved it in my local and edited function changePageTitleBack() , i have added "if else statement " at the end. after lunch if you have time we can look together..
