### ISSUE TITLE
accessability - Leere alt-Attribute für Layoutgrafiken

### ISSUE THREAD

**Issue by karlbrink** [GDI-HE/GeoPortal.rlp#11]
**BITV/WCAG-Prüfschritt: „Layoutgrafiken haben leere alt-Attribute.“**

Die Layoutgrafik „No Image“ trägt den Alternativtext: „Umrissgrenzen um das Gebiet auf der Karte“. Bilder ohne Inhalt wie z.B "no Images" dürfen keine Alt-Beschreibung besitzen.

![grafik](https://user-images.githubusercontent.com/85093749/145195608-2b569a5b-b5ea-4fc6-99ed-64cfc115cce9.png)

**Lösungsvorschlag:**
Für die No-Image Layoutgrafik muss ein leeres HTML alt-Attribut verwendet werden.

**Comment by Andreasr28** [comment]
Question: does the commit above solves the issue? Doesn't look like that here https://www.geoportal.hessen.de/search/

![grafik](https://user-images.githubusercontent.com/75111073/181818386-5a6a319d-4df8-4180-90b1-9b253f7c0e31.png)

**Comment by karlbrink** [comment]
> Question: does the commit above solves the issue? Doesn't look like that here https://www.geoportal.hessen.de/search/
> 
> ![grafik](https://user-images.githubusercontent.com/75111073/181818386-5a6a319d-4df8-4180-90b1-9b253f7c0e31.png)

commit has nothing to do with the issue
