### ISSUE TITLE
Inhalte gegliedert mit geeigneten HTML Elementen

### ISSUE THREAD

**Issue by karlbrink** [GDI-HE/GeoPortal.rlp#13]
**BITV/WCAG-Prüfschritt: „Absätze und Texthervorhebungen sind mit geeigneten Strukturelementen ausgezeichnet.“**

Die Texte unter „Meistgenutzte Karten“ stehen nicht in einem HTML-Absatzelement. Z.B. ist die Überschrift einer Kachel „Boris Hessen“ lediglich per CSS fett hervorgehoben.

![grafik](https://user-images.githubusercontent.com/85093749/145793184-a4bc1096-cde2-4f8e-abeb-80fa6227272c.png)

**Lösungsvorschlag:**
1. Die Texte in HTML-Absatzelement einbinden.
2. „Boris Hessen“ in ein HTML Absatzelement (`<p></p>`) einbinden und für die Hervorhebung zusätzlich in ein HTML strong-Element (`<strong></strong>`) einbinden - ODER wenn möglich als Überschrift definieren - Überschriftenreihenfolgen beachten!

**Comment by Don-King-Kong** [comment]
Für die Umsetzung wurden folgende Änderungen getätigt:

1. Es wurde die CSS Schriftformatierung  **`font-weight`** auskommentiert.
 Dafür wurde die CSS Datei ` GeoPortal.rlp/useroperations/static/useroperations/css/favourite_wmcs.css ` wie folgt angepasst:

```
.tile-header{
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 10px;
    color: var(--primary)
   /*
    font-weight: bold;
    */
    flex-direction: column;
    /*
    height: 70px;
    */
```
2. Wurden HTML-Absatzelemente und HTML-Strongelemente eingefügt.
Dafür wurde die HTML-Datei `/data/GeoPortal.rlp/useroperations/templates/landing_page.html` wie folgt angepasst:

```
 92  <div class="tile-header" data-id="WMC={{result.id}}">
 93                 <div class="tile-title">
 94                  <p><strong>{{ result.title|safe }}</strong></p>
 95                 </div>
```

und

```
128             <div id="show-all-tile-content" class="tile-header">
129                 <div class="tile-title">
130                  <p><strong>{% trans 'Show all' %}</strong></p>
131                 </div>
```

![kacheln_01](https://user-images.githubusercontent.com/74015261/150347434-25b7a263-92ad-4560-aa65-d5edc24d46b7.PNG)

**Alternative Lösung** zum einfügen von HTML-Absatzelemente und HTML-Strongelemente können auch die Kachel-Titel als eine Überschrift definiert werden.

`130                  <h3>{% trans 'Show all' %}</h3>`

Dabei wird die Überschriften-Hierarchie eingehalten. Allerdings gibt es eine sichtbare Abweichung der Schriftgröße, falls man sich für den alternativen Lösungsansatz entscheidet, müsste ggf. die Schriftgröße mittels` style="font-size: `angepasst werden


![kacheln_02](https://user-images.githubusercontent.com/74015261/150351201-681678bc-74ec-4b91-947b-c74666b96855.PNG)

**Comment by Andreasr28** [comment]
Based on the comments above, it seems to be fixed for the headlines! 
Nice!

What about the description text (tile-content-abstract) it was mentioned wasn't it? 
Could the approach therefor be transfered ?

**Comment by Don-King-Kong** [comment]
The tile descriptions can be checked @ prototype
