### ISSUE TITLE
Sprungmarke fuer Hauptinhalt

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#16]
**BITV/WCAG-Prüfschritt: „Seitenbereiche sind durch Überschriften, Sprunglinks oder WAI ARIA document landmarks erschlossen, Frames und Iframes haben sinnvolle Titel.“**

**Problem:**  Der Kopfbereich, die Navigation und der Footer weisen Sprungmarken auf, jedoch nicht der Hauptinhalt.

Kein Bild

**Lösungsvorschlag:** Den Hauptinhalt in ein main-Element ` (<main></main>)` einschließen.

**Comment by Don-King-Kong** [comment]
Für die Umsetzung wurden folgende Änderungen getätigt:

In der HTML-Datei `GeoPortal.rlp/templates/base.html` wurden HTML-Main-Attribute hinzugefügt.
```
201  <main>
202     <div id="body-content" class="body-content {% if not sidebar_closed %} sidebar-open {% endif %}">
203
204     {% block body %}
205     {% endblock %}
206     </div>
207     {% if cookie is None %}
208         {% include 'cookie_banner.html' %}
209     {% endif %}
210   </main>
211 </body>
212
213 <footer>

```
![sprungmarke_01](https://user-images.githubusercontent.com/74015261/150524217-ed0b67ec-3db1-41d3-ad6c-c857aba56f01.png)

Ehrlich gesagt weiß ich nicht ob das so richtig ist, aber die Seite funktioniert noch!

**Comment by Andreasr28** [comment]
Seems good to me .. 
I compared test.geoportal.hessen.de with your implementions prototyp.geoportal.hessen.de

**Comment by karlbrink** [comment]
we should check this in a bigger view for the whole page. a good article aout the goals and examples is here: https://www.barrierefreies-webdesign.de/knowhow/landmark-roles/
