### ISSUE TITLE
cookie-banner adjustment

### ISSUE THREAD

**Issue by karlbrink** [GDI-HE/GeoPortal.rlp#17]
**the cookie-banner is not compliant**

- do not overlap footer: Nutzungsbedingungen, Impressum and Datenschutzhinweis
- rename Button: sth else
- do not overlap article content from Nutzungsbedingungen, Impressum and Datenschutzhinweis
- adjust content text: its all about technically needed cookies and focus on different useconstraints of different ressources

![Issue_Cookie_Banner](https://user-images.githubusercontent.com/75111073/151535858-4124abfe-6ac4-4249-a86b-41b4558c059d.PNG)

**Comment by Andreasr28** [comment]
Can't chekc the last commit .. positon is still bottom of page

Would be good on top i could imgaine.

![Bottom](https://user-images.githubusercontent.com/75111073/151993468-9676091e-2544-4ead-8826-b331573d39c0.PNG)

**Comment by karlbrink** [comment]
Ready for review

**Comment by Andreasr28** [comment]
- terminal mobil \ chrome > ok
- terminal tablet \ firefox > ok
