### ISSUE TITLE
GUI switch

### ISSUE THREAD

**Issue by Andreasr28** [GDI-HE/GeoPortal.rlp#21]
The registered user can select his pefered gui and this gui will start when open the map viewer. 

If the  registered user switches the admitted gui and performs searching with adding of ressouces, then i would aspect that the last gui selected, would be shown. 
That is not the case.
The gui falls back to the  pefered gui.

**Comment by karlbrink** [comment]
opend issue in parent project: https://github.com/mrmap-community/GeoPortal.rlp/issues/37
