### ISSUE TITLE
W3C Markup Validation Error

### ISSUE THREAD

**Issue by karlbrink** [GDI-HE/GeoPortal.rlp#30]
**https://validator.w3.org/**

Use: https://test.geoportal.hessen.de/

_Element [head](https://html.spec.whatwg.org/multipage/#the-head-element) is missing a required instance of child element title.
Stray start tag html.
Cannot recover after last error. Any further errors will be ignored._

**Comment by karlbrink** [comment]
inside base.html the csrf_token var forced an <input> element outside of the html block - not allowed.
inside the <title> there is a block title var - this breaks the head element.

**Comment by Andreasr28** [comment]
Any suggestions how to deal with this?

**Comment by karlbrink** [comment]
I repaired some basic markup errors already -> see: https://github.com/GDI-HE/GeoPortal.rlp/commit/e8ff0114d353ee8b688d1b55aee85e28fb544086

Now the W3C validator is not aborting anymore. -> see: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftest.geoportal.hessen.de%2F

The further development takes place in the branch https://github.com/GDI-HE/GeoPortal.rlp/compare/master...GDI-HE:GeoPortal.rlp:30_markup_validation

**Comment by muqit-zoarder** [comment]
W3C Markup Validation Error on Linked Open Data Page:

Error link: https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Ftest.geoportal.hessen.de%2Flinked_open_data%2F

We have following markup validation errors:

1.     Error: Start tag a seen but an element of the same type was already open.
2.     Error: Bad value 100% for attribute width on element [iframe](https://html.spec.whatwg.org/multipage/#the-iframe-element): Expected a digit but saw % instead.
3.     Error: The frameborder attribute on the iframe element is obsolete. [Use CSS instead](http://wiki.whatwg.org/wiki/Presentational_elements_and_attributes).
4.     Error: The scrolling attribute on the iframe element is obsolete. [Use CSS instead](http://wiki.whatwg.org/wiki/Presentational_elements_and_attributes).
5.     Error: The element iframe must not appear as a descendant of the a element.
6.     Error: End tag div seen, but there were open elements.
7.     Error: Unclosed element a.
8.     Error: End tag main seen, but there were open elements.
9.     Error: End tag div seen, but there were open elements.
10.     Error: The element button must not appear as a descendant of the a element.
11.     Error: Start tag a seen but an element of the same type was already open.
12.     Error: End tag a violates nesting rules.
13.     Fatal Error: Cannot recover after last error. Any further errors will be ignored.

**Comment by karlbrink** [comment]
needed fix in the mapbender project:
file: mapbender/http/css/linkedDataProxy.css
insert:
`html:not(:root) footer {
     display:none;
}`

**Comment by karlbrink** [comment]
mapbender fix done
https://github.com/GDI-HE/Mapbender2.8/commit/7ae5370cca13e688ff5635f7d65cfa4943789921

**Comment by karlbrink** [comment]
mapbender fix again ;-)
https://github.com/GDI-HE/Mapbender2.8/commit/c31e9374ccc313533b60e53cb4ada1a009864806
