### ISSUE TITLE
Mediawiki based News banner on landingPage needed

### ISSUE THREAD

**Issue by muqit-zoarder** [GDI-HE/GeoPortal.rlp#36]
The newly added "news banner" in GeoPortal-Hessen Landing page required changes in CSS file.

Current situation:
a) The newly built news banner does not fit with "landing-page-body" div element in wide screen
b) updated style properties could be added in correct CSS file

![news_B](https://user-images.githubusercontent.com/98881990/183901549-ecce6802-4729-4049-b1cd-c49007e9554f.PNG)

Solution:

 - 'id' properties can be added in <div class='landing-page-body'>
 
   `<div class="landing-page-body" id= "changeAlert">`

 -  in base.css we can add new required style properties for this id
 `#changeAlert{
    background-color: var(--hesse-lighterblue);
    padding: 15px;
    border: 2px solid transparent;
    margin: 0 10px;
}`
`.landing-page-alert{
    margin:0; 
    border: 2px solid var(--hesse-red);
    background-color: var(--hesse-lighterblue);
    padding: 5px;
}  `
`.landing-page-alert h2{
    text-align: center;
    line-height:1.5;
    margin:0;
    font-size:1em;
} `

>  `<div class="landing-page-body" id= "changeAlert">
    <div class="landing-page-alert">
		<h2 2="">...........</h2>`

**Comment by karlbrink** [comment]
in production i deleted the max-width attribute quick and dirty.

we should try an sustainable approach with the use of mediawiki. The news authors are using mediawiki already for writing the news article. They just prepend the new actual stuff.

Idea: Author should "mark" his text as somthing like "breakingNews", serve a heading and finally the hint on the landingPage is shown automatically with the right Link to the news and his position in the article.

**Comment by muqit-zoarder** [comment]
Idea: if there is no prototype issue or design issue, then we can visualize recent published news direct on landing page (last 4 news or 6 news).

**Comment by dpakprajul** [comment]
A news which is marked by topNews by the author in the mediawiki could be shown in the landing page directly, but not able to show it in a localhost, but localhost/topnews/. The news will be automatically deleted if the maintainance day is over.
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/fd3ab241-c079-4083-80f3-ffd86f5c37ac)

**Comment by Andreasr28** [comment]
So your complete work is documented [here](https://github.com/dpakprajul/landing_page/blob/main/Mediawiki_documentation.md) right?

And i can already transfer the result as a basic configuration for the message area, correct?

**Comment by dpakprajul** [comment]
I would say yes, if it works on the test system without error.

**Comment by Andreasr28** [comment]
Good, then i will apply the  **topNews** template and use the template for the next messages to see if there are any anomalies.

**Comment by dpakprajul** [comment]
@karlbrink 
### Idea
Is is better to use this close button as that user can close and it disappears
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/b08969fc-40fb-4957-9dcb-d3761c4aaa91)

**Comment by karlbrink** [comment]
now the new codebase is available so i will do a rollout of this branch in the test system - then lets check it. 😉

**Comment by Andreasr28** [comment]
Nice :) 
https://github.com/GDI-HE/GeoPortal.rlp/blob/36_Newsbanner/documentation/requirement_topnews_parser.md

**Comment by Andreasr28** [comment]
So @dpakprajul do you have usecase for testing or should i assit?

**Comment by Andreasr28** [comment]
Collection:
- Newsletter GDI-DE
- News Wartung HVBG
- News Wartung GDS
- UPDATE Geoportal HE
- News INSPIRE
- Besondere News GDI-DE
- News E-Government
