### ISSUE TITLE
W3C Markup Validation Error on Linked Open Data Page

### ISSUE THREAD

**Issue by muqit-zoarder** [GDI-HE/GeoPortal.rlp#37]
https://validator.w3.org/

Use: https://test.geoportal.hessen.de/linked_open_data/

To see the errors, click here: https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Ftest.geoportal.hessen.de%2Flinked_open_data%2F

We have following markup validation errors:
 1. Error: Start tag a seen but an element of the same type was already open.
 2. Error: Bad value 100% for attribute width on element [iframe](https://html.spec.whatwg.org/multipage/#the-iframe-element): Expected a digit but saw % instead.
 3. Error: The frameborder attribute on the iframe element is obsolete. [Use CSS instead](http://wiki.whatwg.org/wiki/Presentational_elements_and_attributes).
 4. Error: The scrolling attribute on the iframe element is obsolete. [Use CSS instead](http://wiki.whatwg.org/wiki/Presentational_elements_and_attributes).
 5. Error: The element iframe must not appear as a descendant of the a element.
 6. Error: End tag div seen, but there were open elements.
 7. Error: Unclosed element a.
 8. Error: End tag main seen, but there were open elements.
 9. Error: End tag div seen, but there were open elements.
 10. Error: The element button must not appear as a descendant of the a element.
 11.  Error: Start tag a seen but an element of the same type was already open.
 12. Error: End tag a violates nesting rules.
 13. Fatal Error: Cannot recover after last error. Any further errors will be ignored.

The further development takes place in the branch https://github.com/GDI-HE/GeoPortal.rlp/compare/master...GDI-HE:GeoPortal.rlp:37_markup_validation

**Comment by karlbrink** [comment]
at least one template is broken somehow - 

i checked it out on one of our systems - only shown page is an maintenance one

..rollback to branch 30_markup_validation

**Comment by karlbrink** [comment]
fixed in #30
