### ISSUE TITLE
User Statistik

### ISSUE THREAD

**Issue by karlbrink** [GDI-HE/GeoPortal.rlp#39]
- copy the wiki code to some own wiki site....
  - https://www.geoportal.rlp.de/mediawiki/index.php/Statistiken
- provide a link in the geoportal frontend to take a look

**Comment by Andreasr28** [comment]
Template:
[Statistik_RLP.txt](https://github.com/GDI-HE/GeoPortal.rlp/files/9477555/Statistik_RLP.txt)

Path to the graphics HE
[(https://www.geoportal.hessen.de/metadata/)]

Darft page
[(https://test.geoportal.hessen.de/mediawiki/index.php/Statistik)]

**Comment by karlbrink** [comment]
can you make a link somewhere in the test-system with the route /article/user_statistics?

**Comment by Andreasr28** [comment]
Changes and adaptations  from Karl:
https://test.geoportal.hessen.de/article/Statistik/

Looks better even mobil.

**Comment by Andreasr28** [comment]
Draft adopted 

- https://test.geoportal.hessen.de/article/Statistik/ 
- https://www.geoportal.hessen.de/article/Statistik/

Issue Closed.
