### ISSUE TITLE
Bedienung

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#41]
### Prüfschritt 2.1.1.a Ohne Maus nutzbar
> BITV/WCAG-Prüfschritt: „Auch ohne Maus können alle wesentlichen Funktionen und Inhalte genutzt werden.“

**1. Issue:** Einige Bedienelemente sind nicht mit der Tastatur zu erreichen. Zudem sind diese im HTML-Quelltext nicht als Bedienelement ausgezeichnet (siehe Abbildung 23, Abbildung 24 und Abbildung 25).

![abb_23](https://user-images.githubusercontent.com/74015261/188587696-a1864ad9-85bd-412d-a3d2-010963e2c341.png)
Abb 23
![abb_24](https://user-images.githubusercontent.com/74015261/188588051-873fe3f2-3098-46f3-bca9-e77734a7b41a.png)
Abb 24
![abb_25](https://user-images.githubusercontent.com/74015261/188588125-8b2f56df-0ab1-4296-892b-7762a685a58d.png)
Abb 25

**LBIT:** Mit der Tastatur nicht erreichbare Bedienelemente bedeuten Probleme für Anwenderinnen und Anwender, welche zur Bedienung der Webseite auf die Tastatur angewiesen sind. Diese können bestimmte Bereiche oder Funktionen der Seite nicht verwenden. Da die Bedienelemente zudem nicht entsprechend im HTML-Quelltext ausgezeichnet sind, können Nutzerinnen und Nutzer technischer Hilfsmittel diese nicht als solche wahrnehmen. Für das betreffende Element muss ein semantisch passendes HTML-Element verwendet werden, beispielsweise ein button-Element. Dieses lässt sich problemlos mit der Tastatur erreichen und ist auch mit technischen Hilfsmitteln problemlos wahrnehmbar. Alternativ ist es ebenfalls möglich, das betreffende Bedienelement mit dem Attribut tabindex=“0“ und mittels des role-Attributs mit der Rolle eines semantisch passenden Elements, beispielsweise role=“button“, zu versehen. In beiden Fällen muss sichergestellt werden, dass das Bedienelement mit der Enter-Taste der Tastatur aktiviert werden kann.

---
**2. Issue:** Die markierten Elemente sind nicht mit der Tastatur bedienbar (siehe Abbildung 26).

![abb_26](https://user-images.githubusercontent.com/74015261/188588518-d88c1578-486a-46c1-9e3f-cec553ec5a7a.png)
Abb 26

---

**3. Issue** Das Akkordeon ist für Tastaturnutzer nicht auf oder zu klappbar

![abb_27](https://user-images.githubusercontent.com/74015261/188588668-352ccadd-0299-437c-b5db-49658f8811ed.png)

**LBIT:** Die Tastaturbedienung muss möglich sein

**Comment by Don-King-Kong** [comment]
**1. Issue**
Part 1.1: der Cookie Banner ist jetzt mit der Tastatur erreichbar und kann über Enter geschlossen werden.
Part 1.2: Der BackToTop button war schon mit der Tastatur ansteuerbar, hab es jetzt als button spezifiziert und die Farbe geändert
Part 1.3: habe ich auf anhieb nicht verstanden, schau es mir noch zu einem späteren Zeitpunkt an.

**Comment by Andreasr28** [comment]
3. Issue Das Akkordeon ist für Tastaturnutzer nicht auf oder zu klappbar 

Mit Tab springt man von äußeren Bedienelementen, welche ansteuerbar sind, direkt in die erste Akkordeonfacette nämlich den Filter .. dort schon drin erst zur Treffer pro Seite und dann zu Sortieren nach .. mehr aber nicht.

Mann keine Gelgeenheit zwischen Filter - Datensätze usw. zu wechseln noch den offenen Filter zu schließen.

Dann kann mann vier fünf mal Tab drücken sieht aber nicht und es passiert auch nichts wenn man Return drück dazwischen. Erst wieder wenn Tab in der Fußleiste ankommt.
