### ISSUE TITLE
Farbe und Kontraste

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#42]
### Prüfschritt 1.4.1.a Ohne Farben nutzbar
> BITV/WCAG-Prüfschritt: „Die Wahrnehmung von Farben ist für die Bedienung oder das Verständnis der Inhalte nicht erforderlich.“

**1. Issue:** Die Seite ist nicht ohne Farben nutzbar. Das Bild mit dem Text OPEN DATA zeigt nur farblich seinen Zustand an (siehe Abbildung 15).

![abb_15](https://user-images.githubusercontent.com/74015261/188591769-2312bbb3-4803-4aef-850d-f123a60e11a3.png)
Abb 15
 
Menschen mit Farbblindheit oder Farbschwäche können die Zustände (Aktiviert oder Deaktiviert) nicht unterscheiden. Eine andere farbunabhängige Hervorhebung muss ergänzt oder das Bild muss durch eine klassische HTML checkbox ersetzt werden.
Die Downloadlinks „Architekturkonzept Version 5.1 (PDF / 3.11 MB) und „Die Erklärung zu Barrierefreiheit als Download“ unterscheidet sich nur durch die Schriftfarbe vom restlichen Text, dies ist unzulässig (siehe Abbildung 16 und Abbildung 17).

![abb_16](https://user-images.githubusercontent.com/74015261/188591984-4288cefc-e4d1-40d6-885f-9b1b8991686d.png)
Abb 16

![abb_17](https://user-images.githubusercontent.com/74015261/188592022-e06038c8-710c-4e5c-b842-be5da25e6ff3.png)
Abb 17

**LBIT:** Die Links müssen visuell hervorgehoben werden, dies kann durch eine andere Schriftart, Schriftgröße, Unterstreichung, … oder auch mit z. B. einem vorangestellten Piktogramm erfolgen. Personen mit Farbblindheit können die Eigenschaft Link im Fließtext nicht erkennen.

---
### Prüfschritt 1.4.3.a Kontraste von Texten ausreichend
> BITV/WCAG-Prüfschritt: „Texte haben ausreichende Helligkeitskontraste.“

**2. Issue:**  Der verwendete Farbkontrast für den Texts im Suchfeld, von der Schriftfarbe zum Hintergrund, erfüllt nicht die Anforderung (siehe Abbildung 18).
![abb_18](https://user-images.githubusercontent.com/74015261/188592384-07e3ec75-904e-42d8-8cd0-3451c211a782.png)
Abb 18

**LBIT:** Der Kontrast muss mindestens 4.5:1 entsprechen.

---
**3. Issue:** Die verwendeten Kontraste der Schriftfarbe im OPEN DATA zum Hintergrund, erfüllen in aktivierten und deaktivierten Modus, nicht die Anforderungen (siehe Abbildung 19 und Abbildung 20).

![abb_19](https://user-images.githubusercontent.com/74015261/188594157-8cea3806-9a54-4d82-a7c6-7486931ada54.png)
Abb 19

![abb_20](https://user-images.githubusercontent.com/74015261/188594260-b463f62e-2de4-4cd2-ab7e-d74e1f13e6c6.png)
Abb 20

**LBIT:** Der Kontrast muss mindestens 4.5:1 entsprechen. Kontraste können mit unterschiedlichen Tools überprüft werden. Z. B. mit dem kostenlosen Programm: Color Contrast Analyser: (https://developer.paciellogroup.com/resources/contrastanalyser/). Die Kontraste der Mouse-Over Effekte müssen auch berücksichtigt werden.

---
**4. Issue:** Der verwendete Kontrast von Schriftfarbe zum Hintergrund erfüllt nicht die Anforderungen (sehe Abbildung 21).

![abb_21](https://user-images.githubusercontent.com/74015261/188594521-ea4c8b74-670a-4379-b411-fe426298966f.png)
Abb 21

**LBIT:** Der Kontrast muss mindestens 4.5:1 entsprechen.

---
### Prüfschritt 1.4.11.a Kontraste von Grafiken und Bedienelementen ausreichend
> BITV/WCAG-Prüfschritt: „Die für die Identifizierung notwendige visuelle Information von informationstragenden Grafiken und grafischen Bedienelementen sowie deren Zuständen soll einen Kontrast von mindestens 3:1 zu angrenzenden Farben haben.“

**5. Issue:** Die Rahmen der Eingabefelder bieten zu wenig Kontrast. Der Colour Contrast Analyser ermittelt einen Wert von 1,3:1, dies ist ungenügend (siehe Abbildung 22).
![abb_22](https://user-images.githubusercontent.com/74015261/188594980-d570ba2e-1058-4b41-9074-1cbb10be84cd.png)

**LBIT:** Die Kontrastanforderung von mindestens 3:1 muss erfüllt werden.

**Comment by Don-King-Kong** [comment]
Eine Seite die hilft Farbkontraste zu finden: https://contrast-finder.tanaguru.com/

**Comment by Don-King-Kong** [comment]
**ACHTUNG:** 
Bitte nicht einfach mergen, hier haben sich paar fehler eingeschlichen bzw. haben sich neue und alte Arbeiten vermischt.

**Comment by Don-King-Kong** [comment]
Bei den Issues rund um "Open Data" habe ich rücksprache bedarf, weshalb ich sie erstmal ausgelassen hab.

**Comment by Andreasr28** [comment]
> **ACHTUNG:** Bitte nicht einfach mergen, hier haben sich paar fehler eingeschlichen bzw. haben sich neue und alte Arbeiten vermischt.

? Gibt es hier etwas was wir generell bei der Arbeit mit Github beachten sollten?

**Comment by Andreasr28** [comment]
Issue 1 Siehe Issue 3. 
Die Grafik bzw. das Logo hat hier nur Wiedererkennung vor der Funktion eines zusätzlichen Filterkriteriums .. und das nur eine nicht Barreirebetroffene Person.
 
Issue 3 bezieht sich auf die Filteroption unter Treffer pro Seite und Sortieren. 
Gibt hier aus meiner naiven Sicht ja nur die Möglichkeit, auch um das Kriterieum über Tab ansteuerbar zu machen, dass Krit. in eine Auswahl OpenData an aus zu verwandelen ..wie Treffer und Sortieren. Damit ist dann die Farbgebung hier als Anspruch auch gelöst.
