### ISSUE TITLE
accessability - Aussagekräftige Beschreibungen

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#45]
### Prüfschritt 1.1.1.a Alternativtexte für Bedienelemente
> BITV/WCAG-Prüfschritt: „Grafische Bedienelemente haben sinnvolle Alternativtexte.“

- [x] **1. Issue:** Das Linkziel ist nicht genannt und der Alternativtext vermittelt nur eingeschränkt den Bildinhalt (siehe Abbildung 1):

- [x] **2. Issue:** Aus dem Alternativtext der Logos geht das Linkziel nicht hervor. Für Nutzer von assistiver Technologie ist damit unklar, wohin der Link führt (siehe Abbildung 2).

![abb_01](https://user-images.githubusercontent.com/74015261/188658689-2573db11-56ae-406f-afb7-605ee1cd81f5.png)
Abb 1

![abb_02](https://user-images.githubusercontent.com/74015261/188658896-e9b52566-1f08-4b7b-bd1b-95c05323605a.png)
Abb 2

**LBIT:** Der Alternativtext muss die beiden Kriterien Bildbeschreibung und Nennung des Linkziels erfüllen.

--- 
### Prüfschritt 1.1.1.b Alternativtexte für Grafiken und Objekte
> BITV/WCAG-Prüfschritt: „Informative Grafiken und Bilder haben sinnvolle Textalternativen. Objekte wie Video- und Audio-Dateien sowie Applets haben zumindest kurze beschreibende Textalternativen.“

- [x] **3. Issue:** Mit Hilfe eines Auge Piktogramms wird sehenden Nutzenden die Bedeutung der nebenstehenden Zahl vermittelt (Aufrufe des Elements = ‚views‘), diese Information steht blinden Nutzenden nicht zur Verfügung, da das Symbol keine Beschriftung hat (siehe Abbildung 4).

![abb_04](https://user-images.githubusercontent.com/74015261/188659703-3c53df4f-185b-4b55-a94c-5464c9da3f4b.png)
Abb4

**LBIT:** Eine Beschriftung muss hinzugefügt werden. Dies kann z. B. mit **_aria-label_** erfolgen.

---

### Prüfschritt 1.1.1.c Leere alt-Attribute für Layoutgrafiken
> BITV/WCAG-Prüfschritt: „Layoutgrafiken haben leere alt-Attribute.“

- [x] **4. Issue:** Sowohl die Platzhaltergrafiken, als auch die Miniaturvorschau sollte als Layout- bzw. Schmuckgrafik betrachtet werden. Hier fehlt das leere HTML alt-Attribut (siehe Abbildung 5).

![abb_05](https://user-images.githubusercontent.com/74015261/188660237-baa3f7c7-ca25-4217-9ebc-5c7f114d9893.png)
Abb 5

**LBIT:** Ein leeres HTML alt-Attribut (alt=““) muss hinzugefügt werden um den Screenreadern zu signalisieren, dass es sich um eine Layoutgrafik handelt. Für die No-Image Layoutgrafik muss ein leeres HTML alt-Attribut verwendet werden.

---
### Prüfschritt 1.1.1.d Alternativen für CAPTCHAs
> BITV/WCAG-Prüfschritt: „Der Alternativtext des Bildes in einem bildbasierten CAPTCHA beschreibt dessen Zweck. Mindestens eine nicht bildbasierte CAPTCHA-Alternative ist vorhanden.“

- [ ] **5. Issue:** Ein Nutzender von Screenreadern kann das CAPTCHA nicht eigenständig lösen, da der Inhalt des Bildes nicht programmatisch ermittelbar ist (siehe Abbildung 6)

![abb_06](https://user-images.githubusercontent.com/74015261/188661130-23bdc4ff-8bd1-4af8-b70f-b8e8e2fbee8d.png)
Abb 6

**LBIT:** Es muss eine Alternative für blinde Menschen angeboten werden, ansonsten ist es für diese Gruppe nicht möglich das Anmeldeformular abzusenden. Auch für Personen mit Seheinschränkungen kann das CAPTCHA unüberwindbar sein.

### Prüfschritt 2.4.4.a Aussagekräftige Linktexte
> BITV/WCAG-Prüfschritt: „Linktexte sind durch den Linktext selbst oder über den programmatisch ermittelbaren Kontext aussagekräftig.“

- [ ] **6. Issue:** Das Bedienelement zum erneuern des CAPTCHA Bildes ist technisch ein HTML link. Das hierfür verwendete Schriftzeichen wird von zwei der getesteten Screenreadern als „Kreispfeil im Uhrzeigersinn“ benannt. Das Linkziel bzw. die Funktion ist nur eingeschränkt ersichtlich (siehe Abbildung 29).

![abb_29](https://user-images.githubusercontent.com/74015261/188662761-a1163fd4-93b9-4ad1-9c97-b34b4c38b990.png)
Abb 29

**LBIT:** Es kann nicht garantiert werden, dass alle Screenreader das Symbol richtig interpretieren oder blinde Nutzende die Beschreibung des Symbols mit der Funktion verbinden. Eine Beschriftung sollte gewählt werden, die eindeutig den Zweck des Links wiedergibt, dies kann hier auch mit einem **_aria-label_** erfolgen. Denkbar ist hier auch die zusätzliche vergabe einer aria Rolle (button), um der visuellen Repräsentation gleich zu kommen.

----

### Prüfschritt 2.4.6.a Aussagekräftige Überschriften und Beschriftungen
> BITV/WCAG-Prüfschritt: „Überschriften und Beschriftungen sind klar und aussagekräftig.“

- [x] **7. Issue:**  Für Screenreader Nutzende ist der Button erreichbar, hat jedoch keine programmatisch ermittelbare Beschriftung (siehe Abbildung 30).

![abb_30](https://user-images.githubusercontent.com/74015261/188662283-40aa0d6c-f2f5-49de-8e97-60fd4a984d40.png)
Abb 30

**LBIT:** Eine Beschriftung muss ergänzt werden, dies kann z. B. mit einem **_aria-label_** erfolgen.

**Comment by Don-King-Kong** [comment]
1+2. Issues
Unterschied zwischen ALT- und TITLE-Attribut
Während sich ein ALT Attribut nur auf das <img>-Tag anwenden lässt, ist TITLE ein Universalattribut, welches die meisten HTML Elemente unterstützen. Sein Zweck ist das Hinzufügen von Kommentaren, kurzen Erläuterungen oder zusätzlichen Informationen. Webbrowser zeigen den TITLE-Inhalt beim Überfahren mit der Maus als Tooltip an. Aufgrund der Bedeutung für Barrierefreiheit und Usability sind Alternativtexte für SEO wichtiger als der Bildtitel. Daher ist ALT eine Pflichtangabe, wohingegen TITLE nur sparsam und umsichtig zum Einsatz kommt.

**Comment by karlbrink** [comment]
the captcha can't be changed. only thing is to deactivate it completely
