### ISSUE TITLE
CORS: Access-Control-Allow-Origin: * on APIs

### ISSUE THREAD

**Issue by t-huyeng** [GDI-HE/GeoPortal.rlp#49]
Any reason why most of the APIs and even the OpenAPI specification does not provide a `Access-Control-Allow-Origin: *` - Header?

For example:

```
curl -I \
  'https://www.geoportal.hessen.de/spatial-objects/795/api' \
  -H 'accept: application/json'
HTTP/1.1 200 OK
Date: Wed, 05 Oct 2022 18:43:50 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-XSS-Protection: 1; mode=block
Vary: User-Agent
Content-Type: application/openapi+json;version=3.0
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Set-Cookie:  ....
```

**Comment by t-huyeng** [comment]
The geoportal from Saarland has this Header set properly.

**Comment by t-huyeng** [comment]
The Geoportal RLP says that the usage of ` Access-Control-Allow-Origin: *` should be the default. 
See:  https://www.geoportal.rlp.de/mediawiki/index.php/Vorgaben_der_GDI-DE_zur_Bereitstellung_von_Darstellungsdiensten#Verwendung_von_CORS_Headern

Even they also do not implement this. 
```
curl -I \
  'https://www.geoportal.rlp.de/spatial-objects/307/api' \
  -H 'accept: application/json'
HTTP/1.1 200 OK
Date: Tue, 11 Oct 2022 14:43:26 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-XSS-Protection: 1; mode=block
Vary: User-Agent
Content-Type: application/openapi+json;version=3.0
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Set-Cookie:  ....
```

**Comment by t-huyeng** [comment]
Until now, I also could not find the corresponding part for https://www.geoportal.hessen.de/spatial-objects/ in the code. 
Is this not part of this GitHub-Repo? 
Maybe a recent contributor like @Don-King-Kong or @muqit-zoarder can help here?

**Comment by armin11** [comment]
we found the problem and fixed it ;-) - https://github.com/mrmap-community/Mapbender2.8/commit/f9a9147aae96c7e988f125142199cec57d8ce29b. thanx for the hint - the header was already set for collections and items, but was forgotten for the schema.
@karlbrink will update the fork of hesse shortly.

**Comment by karlbrink** [comment]
@t-huyeng it's fixed now in our system. enjoy and thank you.

**Comment by t-huyeng** [comment]
Thanks! I think this is really helpful if someone wants to use the data / api. 

My small go-script also confirms that the Header is now set correctly see [GitHub Action](https://github.com/t-huyeng/geoportal-openapis/actions/runs/3300021264/jobs/5444048606) (look at `Run go run . -path=../geoportal_he_go.json -geoportalURL=https://www.geoportal.hessen.de/ --save=true`)

This is also true for the RLP and SL Geoportal now.
