### ISSUE TITLE
Alternativtexte für Bedienelemente

### ISSUE THREAD

**Issue by karlbrink** [GDI-HE/GeoPortal.rlp#5]
**BITV/WCAG-Prüfschritt: „Grafische Bedienelemente haben sinnvolle Alternativtexte.“**

1. Der Alternativtext des Hessen-Logos ist mit „Logo der Geodateninfrastruktur“ nicht ausreichend. Der Alternativtext gibt keinen ausreichenden Hinweis auf das Linkziel. 
![grafik](https://user-images.githubusercontent.com/85093749/144405315-ad58c734-9a2f-4b19-ae0e-375639e27dc9.png)
**Lösungsvorschlag:** Einen aussagekräftigen Alternativtext benutzen. Zum Beispiel: “Logo der Geodateninfrastruktur: zur Startseite“.

2.  Das Icon für den „räumlichen Filter“ hat keinen Alternativtext. Das HTML title-Attribut title="Activate spatial filter" reicht nicht aus. 
![grafik](https://user-images.githubusercontent.com/85093749/144405650-dd101f1e-b9df-474d-a3ca-86f47a4648e3.png)
**Lösungsvorschlag:** Das Icon benötigt einen Alternativtext. Zum Beispiel: “Räumlicher Filter“.

3. An mehreren Stellen auf der Seite werden alt-Attribute für Icons benutzt. Dies ist nicht zulässig. 
![grafik](https://user-images.githubusercontent.com/85093749/144405829-76d42e5e-4561-4b07-a816-d6ffeb7bfdfc.png)
**Lösungsvorschlag:** Alternativtexte entfernen und durch Beschriftung ersetzen. Zum beschriften kann aria-label verwendet werden. Alternativ kann das Icon auch via aria-hidden versteckt werden, wenn es für Nutzer assistiver Technologien keinen Mehrwert bietet. Alternativtexte sind für HTML img-Elemente vorgesehen.

4. Das Icon „Menü“ ist nur mit Menü beschriftet, und gibt keinen Aufschluss über die eigentliche Funktion wieder. 
![grafik](https://user-images.githubusercontent.com/85093749/144405938-7ef3b976-17a6-4c36-92c3-a82090df7587.png)
**Lösungsvorschlag:** Das Element korrekt via aria-label=“Menü auf- oder zuklappen“ beschriften.

**Comment by Andreasr28** [comment]
Ticketinhalt verstanden. Als Vorlage für die Tickets zum Projekt verwenden.

**Comment by Don-King-Kong** [comment]
**1. Problem:** 
 in der Datei` GeoPortal.rlp/templates/base.html` wurde die Zeile 44 angepasst:
 ` alt="{% trans 'Logo of the spatial data infrastructure organization: to the homepage' %}"`
 in der Datei ` GeoPortal.rlp/locale/de/LC_MESSAGES/django.po ` wurden die Zeilen 802 bis 804 angepasst:
 `802 #: templates/base.html:42 useroperations/templates/landing_page.html:**44**`
 `803 msgid "Logo of the spatial data infrastructure organization**: to the homepage**"`
 `804 msgstr "Logo der Geodateninfrastruktur**: zur Startseite**"`

![alt_1](https://user-images.githubusercontent.com/74015261/148556065-10b8a1fa-8f35-4460-9ac1-474bed983703.PNG)

**2. Problem:**
 in der Datei ` GeoPortal.rlp/locale/de/LC_MESSAGES/django.po ` wurden die Zeilen 1682 bis 1684 hinzugefügt:
 `1682 #: GeoPortal.rlp/templates/base.html:53`
 `1683 msgid "Activate spatial filter"`
 `1684 msgstr "Räumlichen Filter aktivieren"`

![activate_spatial_filter_1](https://user-images.githubusercontent.com/74015261/148556627-f0c47f78-3e91-4bf7-bf53-a2ea4322b583.PNG)


**3. Problem:**
 Verstehe ich nicht so richtig :(

**4. Problem**
 in der Datei ` GeoPortal.rlp/locale/de/LC_MESSAGES/django.po ` wurden die Zeilen 823 und 824 angepasst:
` 823 msgid "Open and close menu"`
` 824 msgstr "Menü auf- oder zuklappen"`

![menue_01](https://user-images.githubusercontent.com/74015261/148557054-c1fb6ed0-6480-420d-90b3-b18677400b4d.PNG)

**Comment by Andreasr28** [comment]
Problem 3. .. in case i get it right then the problem is that the icons ..nearly evry icon like "maps"
![Icons](https://user-images.githubusercontent.com/75111073/152027491-56b7a709-2a41-4b74-b421-3433fdee1c07.png)

uses this class wit the alt-attribut .. 
![grafik](https://user-images.githubusercontent.com/75111073/152027294-ada18847-1350-49ea-98fb-02c014abdae2.png)

recommended is labeling with aria hidden attribut like <p aria-hidden="true">

**Comment by Don-King-Kong** [comment]
Thank you Andreas for your explanation. Okay, if I have understood it correctly, for all icons, we have replace every alt-description with a aria-label-description?
