### ISSUE TITLE
Farb-Kontraste anpassen

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#6]
Auf der Startseite sind manche Farbkonstrastverhältnisse nicht aussreichend. 

1. **BITV/WCAG-Prüfschritt: „Texte haben ausreichende Helligkeitskontraste.“**
**Problem:** Die weiße Schrift im Menü, wenn der Menüpunkt aktiv ist, bildet einen zu geringen Kontrast zum hellblauen Untergrund. Der Colour Contrast Analyser ermittelt einen Wert von 2,7:1. 

Abbildung Geoportal
![Farbkonstras_01](https://user-images.githubusercontent.com/74015261/144445870-559dad24-deef-4a10-94f3-3edf38646544.png)

Abbildung Contrast Analyser
![Farbkonstras_02](https://user-images.githubusercontent.com/74015261/144446116-f99f4b76-c5c6-49b9-bda7-59d88d0c70f0.png)

**Lösungsvorschlag:** Den Kontrast der Schrift erhöhen. Für Schriftgrößen unter 24px muss das Kontrastverhältnis bei 4,5:1 oder höher liegen. Für große Schriften 3:1.

2. **BITV/WCAG-Prüfschritt: „Die für die Identifizierung notwendige visuelle Information von informationstragenden Grafiken und grafischen Bedienelementen sowie deren Zuständen soll einen Kontrast von mindestens 3:1 zu angrenzenden Farben haben.“**
**Problem:** Im Hauptmenü befindet sich hinter dem Menüpunkt „Meldungen“ ein Icon mit einem Ausrufezeichen, sobald eine neue Meldung eingestellt wurde. Dieses Icon hat einen zu geringen Kontrast. Der Colour Contrast Analyser ermittelt einen Wert von 1,4:1. 

Abbildung Geoportal
![Farbkonstras_04](https://user-images.githubusercontent.com/74015261/144446710-b83a84c8-97a5-44df-a2c3-7ff1b15e4e65.png)

Abbildung Contrast Analyser
![Farbkonstras_03](https://user-images.githubusercontent.com/74015261/144446764-b3cf1620-5c47-47ba-8ba2-333403131770.png)

**Lösungsvorschlag:** Der Kontrast muss erhöht werden. Der Kontrast von grafischen Bedienelementen muss einen Kontrast von mindestens 3:1 haben.

**Comment by Don-King-Kong** [comment]
Unabhängig davon das ein neues Layout geplannt ist, habe ich für dieses Issues eine "schnelle" Lösung vorbereitet.

1. **Lösungsvorschlag**
![kontrast_blau](https://user-images.githubusercontent.com/74015261/144607212-4f88f5c7-5efa-45bd-bfe8-1f38785836be.PNG)
**Umsetzung:** `/data/GeoPortal.rlp/useroperations/static/useroperations/css/base.css:878`
> .sidebar-area-title:hover {
>     cursor: pointer;
>     background-color: **#0362B9**;
>     color: white;
> }

2. Lösungsvorschlag
![kontrast_gruen](https://user-images.githubusercontent.com/74015261/144608111-e07d8a76-4c7a-485c-94a4-dd1f0631c4f0.PNG)
**Umsetzung:** `/data/GeoPortal.rlp/useroperations/static/useroperations/js/frontpage.js`

> position: absolute;
> margin-left: 5px;
> color: **green**;

Allerdings werden die Änderungen nicht übernommen, auch nicht nach einem Apache2 Restart.

**Comment by karlbrink** [comment]
Hi.
Damit die Änderungen übernommen werden, muss noch der Schritt aus dem Handbuch Kap. 8.11 durchgeführt werden.

Des Weiteren sollen Farb-Variablen verwendet werden. Siehe dazu color_schema.css.

Die Anpassung der Farbe des Icons (neue Meldungen) zu "green" ist nicht ausreichend (Es gibt eine grüne Variable in der color_schema.css die evtl. passt: --success-green). Beim "hovern" und "aktiviertem" Menüpunkt Meldungen ist "green" zu dunkel - es müsste dann z.B. weiß sein. 
Das einfachste wäre eine Farbe die in beiden Zuständen ausreichenden Kontrast bietet.

Im neuen Design gibt es z.B. keine Hintergrundfarbe mehr für die Menüpunkte , so dass dieses Problem obsolet wird.

**Comment by Andreasr28** [comment]
Anyway .. i like the quick fix :)
