### ISSUE TITLE
Password Criteria

### ISSUE THREAD

**Issue by dpakprajul** [GDI-HE/GeoPortal.rlp#70]
When a user tries to register their profile, the following message is seen:
### Das Passwort entspricht nicht den spezifizierten Kriterien, Sie benötigen mindestens 9 Zeichen, erlaubte Sonderzeichen: @#$%&+=!:-_ 

The password which I tried to test is **hvpat-4n_18p_ec7z-pt98**. But the password without `-` sign works perfect.

The code is in [Geoportal.rlp/useroperations/views.py](https://github.com/GDI-HE/GeoPortal.rlp/blob/master/useroperations/views.py):536
 if re.match(r'[A-Za-z0-9@#$%&+=!:-_]{9,}', form.cleaned_data['password']) is None:

The possible error and its solution might be:
The issue seems to be with the `-` character in your regular expression. In a character set (`[]`), the `-` character is used to specify a range. For example, `A-Z` matches any uppercase letter, and `0-9` matches any digit.

When `-` is placed between other characters (like `:-_`), the regular expression engine tries to interpret it as a range. In this case, it's trying to interpret `:-_` as a range from `:` to `_`, which is not valid.

To match a literal `-` character, we might need to escape it with a backslash (`\-`), or place it as the first or last character in the character set.

```python
if re.match(r'^[A-Za-z0-9@#$%&+=!:_\-]{9,}$', password) is None:
    #print(password)
    messages.error(request, _("Password does not meet specified criteria, you should have at least 9 characters, allowed special chars are: @#$%&+=!:_-"))
    return redirect('useroperations:register')
```

**Comment by dpakprajul** [comment]
### Idea
Since we are using django, can't we use django password validation? It will also give the ValidationError in the browser and would also be more secure.

```python
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

try:
    validate_password(form.cleaned_data['password'])
except ValidationError as e:
    messages.error(request, e.messages)
    return redirect('useroperations:register')
```
instead of  
```python
if re.match(r'[A-Za-z0-9@#$%&+=!:-_]{9,}', form.cleaned_data['password']) is None:
            messages.error(request, _("Password does not meet specified criteria, you should have at least 9 characters, allowed special chars are: @#$%&+=!:-_"))
            return redirect('useroperations:register')
```
### I had made some checks:
when I use only 4 characters: 1234
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/6f47c7d8-4625-48ce-8b62-9ee043805bdb)


when I use the regular numbers: 1234567890
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/b728ff3f-20e8-42f9-b2e7-aab3fb100f7c)


When I use too common password: education
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/d32bac13-ce0e-408d-a46e-442f6146528e)

Another example of too common password: qwerty12345
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/22e67e27-bc64-4c31-ad09-704312016729)

Check the common phrases here: https://gist.github.com/roycewilliams/226886fd01572964e1431ac8afc999ce

**Comment by muqit-zoarder** [comment]
@dpakprajul yes , we can do that as well, if it is so urgent and if @karlbrink Karl thinks it is necessary for us.

**Comment by dpakprajul** [comment]
@muqit-zoarder The problem was with one of the customer and he wrote to us in email.

**Comment by muqit-zoarder** [comment]
@dpakprajul I have read the email now, our portal is only providing information that a password must need 9 characters, nothing more, as the user mentioned he used 12 lowercase letters, hyphens and underscores and numbers , so some of the special characters might not be allowed, so we can work on this password issue.

**Comment by dpakprajul** [comment]
We checked that when a user used ```-``` sign, this error is shown. But it is mentioned in the error that minus sign ```-``` is allowed: Das Passwort entspricht nicht den spezifizierten Kriterien, Sie benötigen mindestens 9 Zeichen, erlaubte Sonderzeichen: @#$%&+=!:-_
I tried to register in the test system with a password: hvpat-4n_18p_ec7z-pt98 it doesnot work and shows the error message.
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/9892e584-cb8f-4406-9a1e-0487a60ab674)

When tried to registered with hvpat4n_18p_ec7zpt98 by removing minus sign, there is no error and the registering is successful.
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/f933fe1c-193b-4e19-9f97-fba72e917ddb)

**Comment by karlbrink** [comment]
- for now the usage of the buildin django password validation is okay for me. i doublecheck why it wasn't used before.
- in the change profile form a user can also change his password - the enhancement is not yet available there - i tested today
- after sending the form, the validation is performed. if there is a error - the form is erased completely - it would be more userfriendly if the form keeps filled and the wrong field is highlighted. 
- in the password field is only one password hint: 9 characters but in fact there are more after the enhancement yet.
- the criterias shoud be recognized by the user during typing if they are fullfilled - clientside live validation? 
- is the "too common" validation also possible live?

**Comment by dpakprajul** [comment]
# Updates:
### 2) In ChangeProfileForm, the following update is done:
```
password = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'new_password','title': _("Please enter your password with at least 9 characters.")}),label=_("New password"), required=False)
passwordconfirm = forms.CharField(widget=forms.PasswordInput(attrs={'title': _("Password confirmation.")}),label=_("Password Confirmation"))
```
The changes are made as in RegistrationForm()
---
### 3) To prevent the form from erasing:
The problem is exists if the user tries to register an account with a username which is already in the database. When the ```Registration``` is clicked, if there is error, the error message appears and the whole form is removed. With the introduction of the below code in ResistratonForm(request.POST), the problem of form erasing should be removed. Need to be tested as I don't have databank access.
```python
if MbUser.objects.filter(mb_user_name=form.cleaned_data['name']).exists():
                messages.error(request, _("The Username") + " {str_name} ".format(str_name=form.cleaned_data['name']) + _("is already taken"))
                geoportal_context.get_context()['focus_username'] = True
                return render(request, 'crispy_form_no_action.html', {'form': form, **geoportal_context.get_context()})
 ```
Also the validation of password is changed to 
```python
try:
                validate_password(form.cleaned_data['password'])
            except ValidationError as e:
                messages.error(request, e.messages)
                return render(request, 'crispy_form_no_action.html', {'form': form})
```
The introduction of form in render helps to prevent the form from erasing.
The previous code was:
```python
            if form.cleaned_data['identity'] != "":
                return redirect('useroperations:register')

            if MbUser.objects.filter(mb_user_name=form.cleaned_data['name']).exists():
                messages.error(request, _("The Username") + " {str_name} ".format(str_name=form.cleaned_data['name']) + _("is already taken"))
                return redirect('useroperations:register')

            try:
                validate_password(form.cleaned_data['password'])
            except ValidationError as e:
                messages.error(request, e.messages)
                return redirect('useroperations:register')
```
The ```geoportal_context.get_context()['focus_username'] = True``` is introduced for anchoring to the problem field. For example: If the username is already used and the new user tries to register with the same name, it should prevent from storing it and head the pointer to the username field.

Similarly if the password donot match, the pointer will lead to the password field:
```python 
messages.error(request, _("Passwords do not match"))
                geoportal_context.get_context()['focus_password'] = True
                return render(request, 'crispy_form_no_action.html', geoportal_context.get_context())
```
The focus (pointing to the field) is done in javascript in crispy_form_no_action.html
```
{% if focus_password %}
<script>
    window.onload = function() {
        var passwordField = document.getElementById('password');
        if (passwordField) {
            passwordField.focus();
        }
    }
</script>
{% endif %}

{% if focus_username %}
<script>
    window.onload = function() {
        var usernameField = document.getElementById('username');
        if (usernameField) {
            usernameField.focus();
        }
    }
</script>
{% endif %}
```

![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/2c405bf6-46b4-42d8-a1a5-f389f12c875b)

### 4) Password hint

It's a hint written in the form as attrs and could be shortened as "Please enter your password". I found no any django functions to work out with it.
```password = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'password','title': _("Please enter your password with at least 9 characters.")}),label=_("Password"))```

### 5) Client side validation
Could introduce zxcvbn password validator https://github.com/dropbox/zxcvbn for the client side validation.
Since the django password validator is secure and encrypted, I am not in favour of Client side validation. When zxcvbn used as a django-password-validator, it also work in backend and wouldn't be more functional than django password.
The use of client side validation need some script needed to be included in the project. 
```<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js"></script>```

The Password strength of this validation has strength 0-4. When the strength is less than 3, the user could be exempted from registering (as the cursor will be changed to not-allowed.
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/7986831e-7772-40fe-8af2-a83053436881)
Also the color could be changed if the password is strong enough:
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/d3f5b8fc-1faa-4494-9262-b0ff12d88450)
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/dd94c89a-658a-4c52-ae7a-9f22298c802c)

---
### 6) The too common password 
The too common password that is used by django is not possible. But the above method also takes about 30k common password in account as mentioned in:
https://github.com/dropbox/zxcvbn

### Problems
- There will be two level validation: server and client level.
- When the client level is passed, it is not sure that it will also pass the server password validation (django validation).
- Need to choose between one!

**Comment by dpakprajul** [comment]
### Suggestion:
 ```#user.password = (str(bcrypt.hashpw(form.cleaned_data['password'].encode('utf-8'), bcrypt.gensalt(12)),'utf-8'))
 user.password = make_password(form.cleaned_data['password'])
```

in useroperations/views.py

The password hashing could be replaced by django hashers : make_password instead of library bcrypt. 
### Pros: 
no need to write too much code.

**Comment by Andreasr28** [comment]
Much work., my appreciation.
Two questions please, you mentioned with the mirror lines five and six that
5) client side validation: cam i right this coud be used to solve the points 2-4) ?
6) too common: As you already mentioned there are problems. I would call another one. Are strong passwords (lv 3-4) realy nessecary in our application?

And at last what are the con (there are cons ?) of your suggestions.

**Comment by karlbrink** [comment]
pls take also care about "accessability" criterias
a few of them are mentioned in slightly different usecases. check following issues#9 or #45 #44 #43

**Comment by dpakprajul** [comment]
https://github.com/GDI-HE/GeoPortal.rlp/commit/74250c8f020f0247b8b207edabf8f833349de87e See the updates here.
