### ISSUE TITLE
Remove date from article statistics

### ISSUE THREAD

**Issue by dpakprajul** [GDI-HE/GeoPortal.rlp#74]
URL: https://www.geoportal.hessen.de/article/Statistik/

Siete Zuletzt geändert makes confusion. Should be removed!
As it gives the data of last 24 hours, user can be confused with the date at the top.

![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/9f0e1292-6eb7-4f93-ad45-c4c925c0a132)

**Comment by Andreasr28** [comment]
I will and can do it. What is the problem? I don't get it.

**Comment by dpakprajul** [comment]
I thought due to the date of the change of the page at the top (which is past date) could be confusing to the users. The user wouldn't bother to look closely into the graph when they see that the page is already old (stale). I think, it looks better now 👍 
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/b1e1ec23-423b-4a59-a34b-9378b70382a8)
