### ISSUE TITLE
Unwanted div-box in Search Menu

### ISSUE THREAD

**Issue by dpakprajul** [GDI-HE/GeoPortal.rlp#75]
### Problem
https://www.geoportal.hessen.de/search/
When we go inside Suche in>Info, we can see a lot of Articles. 
There is a box at the end which shouldn't be the part of the page until any content is inserted into it.  
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/cfbd11d6-36b7-47fa-9f4c-b0700ef63655)

### Possible solution:
1) The div box could be hidden in searchCatalogue/templates/search_results.html:60
2) The div should be hidden until any content is loaded or clicked (using js)

What I have tried:
1) Added ```style="display: none;"``` in line 61 (search_results.html)
``` html
<div class="mediawiki-article" style="display: none;">
        </div>
``` 
The change in style removes the empty box and has no negative impact in displaying the clicked content inside the box.

![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/a98c1c66-bdb4-49fc-9a20-f2701a53f188)

**Comment by karlbrink** [comment]
thx @dpakprajul
