### ISSUE TITLE
Coordinate search does not work correctly

### ISSUE THREAD

**Issue by Andreasr28** [GDI-HE/GeoPortal.rlp#76]
[Anfrage_ Suche nach Gauss-Krüger im Kartenviewer.zip](https://github.com/GDI-HE/GeoPortal.rlp/files/13546197/Anfrage_.Suche.nach.Gauss-Kruger.im.Kartenviewer.zip)
Affected function Coordinate search
Coordinate search, should be possible for: 
- UTM 
- GK and 
- Geographical coordinates

To recreate, start the search in [www.geoportal.hessen.de](https://www.geoportal.hessen.de/)
-  change to GK 3 coordinates 
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/75111073/485391a5-1e46-475b-9ae2-08e6b3a7e61f)
- and if you chose the default setting without any typing then
 ... Error message:
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/75111073/5228a842-58ab-4c43-aaba-0df63d60926b)
This is actually a good behaviour as a search without entries makes no sense.

**In testsystem the function works as expected!!**
Correct example Gauß-Krüger: Rechtswert Y = 3461404 m, Hochwert X = 5483498 m. 

### **But **Error Messages and malfunction ****
1. The target coordinates are displayed incorrectly GK coordinates have no descendant coordinates.
2. If empty entries are chosen .. a error message is displayed
### This should not be possible,  a search without entries makes no sense.
3. If valid coordinates are used, another error message is displayed:
> the search doesn not work and
> the wms hintergundkarte stops working
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/75111073/2f1d59b2-4622-4c34-92b9-1102370944f2)
# This is because when the search is started, the scale in the map viewer is set to 1:0 and this scale range is not provided by HiKa.

**Comment by dpakprajul** [comment]
Something I found (might be helpful for debugging):
In the Netzwerkanalyse in the inspector (debugging console), I see the the GetMap request is called with bbox=0,0,0,0. 
The link looks like this (with invalid bbox): 
https://prototyp.geoportal.hessen.de/wms/overview?VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&LAYERS=huek&STYLES=&SRS=EPSG:25832&BBOX=0,0,0,0&WIDTH=1184&HEIGHT=273&FORMAT=image/png;%20mode=8bit&BGCOLOR=0xffffff&TRANSPARENT=TRUE&EXCEPTIONS=application/vnd.ogc.se_xml

When the file is opened I can see the following.
```
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
<ServiceException>
msWMSLoadGetMapParams(): WMS server error. Invalid values for BBOX.
</ServiceException>
</ServiceExceptionReport>
```
But when the same process is done in the test system, the link in the netzwerkanalyse it correct with valid bounding box value:
https://prototyp.geoportal.hessen.de/wms/overview?VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&LAYERS=huek&STYLES=&SRS=EPSG:25832&BBOX=564385.8763493694,5621374.178020689,564548.0442713691,5621474.138042888&WIDTH=683&HEIGHT=421&FORMAT=image/jpeg&BGCOLOR=0xffffff&EXCEPTIONS=application/vnd.ogc.se_xml

**Comment by dpakprajul** [comment]
Also there is a problem in Coordinate system in the production system. In the test system it works fine as: (this is the screenshot of test system)
<img src="https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/59055a0e-f38d-4c95-a83d-5e05f450cbd0" width="400">

But in the test system, when the projection system is selected to Gauß-krüger 3 (DHDN), it doesn't work. That means it again change the option to **Geographische Koordinaten** or **UTM zone 32N** automatically. 

In the network analysis, the link is generated which looks like this:
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/8abe9cba-5e06-488c-aa43-58c3076fdd4f)


To reproduce:
go to: https://www.geoportal.hessen.de/
click on Kartenviewer
Select the Werkzeuge on the top
Select the Koordinatensystem and change the projection system to Gauß-krüger 3 (DHDN)

**Comment by karlbrink** [comment]
i tested right now.... (kartenviewer zurücksetzen) search for coordinates works now. i fixed some spatial_ref_sys entries for epgsg 31466, 31467, 31468, 31469.

**Comment by dpakprajul** [comment]
@karlbrink I looked into it, and worked so far.
I have one suggestion in the koordinaten anzeigen in the toolbox. The coordinates are shown but it is not clear from the tools which coordinate system is it showing. 
What about adding the text before it? 

Before:
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/e67883ce-a01f-473a-b776-e9dd4b594940)

After:
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/5d7d00a9-71d5-47f1-8677-cc938d66f145)

The geoportal rlp is using different coordinate system (Geographic coordinate system in degree, minutes and seconds as well as decimal values). For easiness (google and OSM friendly), I would also recommend the Geographic coordinate system as:
(screenshot from Geoportal rlp)
![grafik](https://github.com/GDI-HE/GeoPortal.rlp/assets/38970123/e7c1b483-aafe-4464-b8d0-435badbb3d40)

**Comment by dpakprajul** [comment]
@karlbrink @Andreasr28  This issue is solved right? We can close the issue if so.

**Comment by Andreasr28** [comment]
I have tested the functions everything works. Issue Done
