### ISSUE TITLE
Hauptmenü in Liste transformieren.

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#8]
**BITV/WCAG-Prüfschritt: „Listen (einschließlich Menüs) sind mit den vorgesehenen HTML-Strukturelementen ausgezeichnet.“**

**Problem:** Das Hauptmenü ist keine Liste

![Hauptmenue_01](https://user-images.githubusercontent.com/74015261/144465986-d6bd5a41-e6d0-40a7-8a41-3b72bebf01f9.png)

![Hauptmenue_02](https://user-images.githubusercontent.com/74015261/144466025-bc99cc49-490e-4081-8cee-757a46e89d47.png)

**Lösungsvorschlag:** Menü in einer ungeordneten Liste darstellen, die einzelnen Menüpunkte in Listeneintragselemente einschließen `(<ul><li></li></ul>)`. Menüs müssen immer als Liste gestaltet werden.

**Comment by Don-King-Kong** [comment]
Bei meinen ersten Versuchen die Menüpunkte in eine Liste zu transformieren, habe ich durch das direkte eintragen`(<ul><li></li></ul>`  in die` base.html` die Formatierung zerschossen.
Ich erinnere mich auch, dass wir die Hilfe-Menü-Unterpunkte im Django-Admin angelegt haben. Evtl, können wir diese Barriere nicht „händisch“ sondern nur generisch/Django-Mittel lösen.

**Comment by karlbrink** [comment]
no, it can be done just inside the template
i will take care of it in issue #20
