### ISSUE TITLE
accessability - Registrierungsvorgang 

### ISSUE THREAD

**Issue by Don-King-Kong** [GDI-HE/GeoPortal.rlp#9]
Beim Registrierungsvorgang müssen folgende Probleme behoben oder nachgebessert werden

- [x] 1. **BITV/WCAG-Prüfschritt: „Beschriftungen von Formularfeldern stehen vor den Eingabefeldern.“**

**Problem:** Das Pflichtfeldsymbol (*) wird erst am Ende des Formulars erklärt.

![pflichtfeld_01](https://user-images.githubusercontent.com/74015261/144468681-74bf6411-646d-4f50-bf9d-6e6f80a93862.png)

**Lösungsvorschlag:** Die Erklärung an den Anfang des Formulars setzen.

- [x] 2. **BITV/WCAG-Prüfschritt: „Listen (einschließlich Menüs) sind mit den vorgesehenen HTML-Strukturelementen ausgezeichnet.“**

**Problem:** Die angemerkten Passworthinweise unter „Passwort muss folgendes enthalten“ muss eine Liste sein

![passwortHinweis_01](https://user-images.githubusercontent.com/74015261/144469205-5ff8ec1d-62eb-4269-81fd-a22a1c829eff.png)

![passwortHinweis_04](https://user-images.githubusercontent.com/74015261/144472161-a9359d62-fb82-4387-89ca-e2e8c9c58160.png)

**Lösungsvorschlag:** Die angemerkten Passworthinweise in ein HTML Listenelement einschließen.

- [x] 3. **BITV/WCAG-Prüfschritt: „Absätze und Texthervorhebungen sind mit geeigneten Strukturelementen ausgezeichnet.“**

**Probleme:** Die Passworthinweise sind in ein HTML b-Element eingebunden. Dies ist nicht zulässig.

![passwortHinweis_02](https://user-images.githubusercontent.com/74015261/144469236-9ac56995-285b-4357-85f2-d695111e40a2.png)

**Lösungsvorschlag:** Die Passworthinweise in ein HTML strong-Element einschließen.

- [ ] 4. **BITV/WCAG-Prüfschritt: „Wird ein Eingabefehler automatisch festgestellt, wird das fehlerhafte Element aufgezeigt und der Fehler wird in Textform beschrieben.“**

**Problem:** Wenn beim Registrierungsvorgang die Passwortfelder nicht übereinstimmen, und versucht wird, das Formular abzusenden, dann erscheint eine Dialogbox mit einem Hinweis. Die Passwortfelder werden jedoch in keiner Weise hervorgehoben.

![passwortHinweis_03](https://user-images.githubusercontent.com/74015261/144470113-0536afc3-1d8a-4b6f-90f1-69facec862cd.png)

**Lösungsvorschlag:**
Formularfelder, deren Inhalt nicht den Vorgaben entspricht, visuell und durch zusätzlichen Text hervorheben.

- [ ] 5. **BITV/WCAG-Prüfschritt: „Für Datentabellen vorgesehenes Mark-up wird nicht für Layouttabellen verwendet.“**

**Problem:** Die Layouttabelle für die Registrierung besitzt nur ein HTML tbody-Element. Dies ist nicht zulässig.

![regestrierung_01](https://user-images.githubusercontent.com/74015261/146564705-f21eff53-7202-46cd-9e4d-317b1ee0af8a.png)

**Lösungsvorschlag:** Das tbody-Element der betreffenden Tabelle entfernen.

**Comment by Don-King-Kong** [comment]
1. Problem 
Der Hinweis zu den Pflichtfeldern wurde an den Anfang des Formulars gesetzt.
Dafür wurde die Datei ` GeoPortal.rlp/useroperations/templates/crispy_form_no_action.html ` editiert.
```
 43       <div class="foot-note">
 44         {% trans '* The field is required.' %}
 45      </div>
```
wurde jetzt nach oben geschoben und wie folgt geändert:
```
16 <div  style="color:gray; font-size:0.8em;">
17         {% trans '* The field is required.' %}
18 </div>
```
Es wurde so geändert, dass es aussieht wie im "Footer". Ich würde empfehlen, den Hinweis min. durch 1em deutlicher hervorzugeben, gffs. können wir auch eine neue Klasse anlegen "Head-Note".

![pflichtfeld_02](https://user-images.githubusercontent.com/74015261/149532682-3e45eede-319d-4c8e-a329-8e61ebdc3165.png)

**2. Problem und 3. Problem**
Die angemerkten Passworthinweise sollen in ein HTML Listenelement eingebunden werden.
B-Elemente sind unzulässig und sollen ersetzt werden, z.B. durch strong Elemente
Dafür wurde die Datei ` GeoPortal.rlp/useroperations/templates/crispy_form_no_action.html ` editiert.

```
20 <div class="sliding" id="password_message">
21    <h3>{% trans 'Password must contain the following:' %}</h3>
22    <p id="special" class="invalid"><b>{% trans 'A special character, these are allowed: @#$%&+=!:-_' %}</b></p>
23    <p id="length" class="invalid"><b>{% trans 'Minimum 9 characters' %}</b></p>
24 </div>
```
p-Elemente wurden durch li-Elemente in einer ungeordneten Liste ersetzt.
b-Elemente wurden durch Strong-Elemente ersetzt.
Darüber hinhaus habe ich die Überschriften Hierarchie angepasst. 

```
 22             <div class="sliding" id="password_message">
 23                 <h2 style="font-size:150%">{% trans 'Password must contain the following:' %}</h2>
 24                 <ul style="list-style-type:none;">
 25                 <li id="special" class="invalid"><strong>{% trans 'A special character, these are allowed: @#$%&+=!:-_' %}</strong></li>
 26                 <li id="length" class="invalid"><strong>{% trans 'Minimum 9 characters' %}</strong></li>
 27             </div>
```
![passwortHinweis_041](https://user-images.githubusercontent.com/74015261/149532748-b24406cb-2dcd-4213-a7e3-344e90945558.png)

Zu Problem 4 habe Abstimmungsbedarf und Problem 5 verstehe nicht richtig und weiß daher nicht genau wie ich es umsetzten soll.

**Comment by Andreasr28** [comment]
Problem 1 .. good ! 
Did you delete the "old" labelling on the bottom?

Problem 2 and 3 .. approach seems good .. may i see the adjustment in the prototype ?

**Comment by Don-King-Kong** [comment]
unfortunately no, the changes are lost with the last update.

Yes i have take out the old-labelling, but a second requirement hint would also be okay.

**Comment by karlbrink** [comment]
i take a look now - i will also perform an master-merge in the relevant branch

**Comment by Andreasr28** [comment]
So thix issue is fixed?

**Comment by Andreasr28** [comment]
Seems still pending .. Can someone please summarise what the goal was or what the expected functionality is ?

Because:
*Pflichtfeld is in the current version explained at the top and bottom of the form and do I no longer receive any information about the characters that can be used in the password.

**Comment by Andreasr28** [comment]
In both applications 

- https://www.geoportal.hessen.de/register/
- https://test.geoportal.hessen.de/register/

- [ ] the registerforms now have a label in front of the form field
- [ ] password instructions 
>  - [ ] Minimum 9 characters
>  - [ ] A special character, these are allowed
